root = "."
tmp_dir = "tmp"

[build]
exclue_dir = ["tmp"]
include_ext = ["go", "html", "css"]
cmd = "go build -o ./tmp/main ."
full_bin = "export ENVIRONMENT=air; export PORT=8080; ./tmp/main"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
