name: wedding
services:
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: db.dockerfile
    command: ["postgres", "-c", "log_statement=all"]