name: wedding
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
  
  web:
    build: .
    depends_on:
      - db
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - ${PORT}:${PORT} 